### PR TITLE
Quickstart guide for crc on macOS

### PR DESCRIPTION
**Pull request by disposab1e**
Hi John,

I used your operator and wrote a small guide. Perhaps you're interested to integrate it.

### CODE REVIEW

**Comment by disposab1e** [comment]
Forgot to mention... great work so far! Works like a charme! 

Happy to share my experience with you!

**Comment by jmckind** [comment]
Thanks @disposab1e! I will run through it and provide feedback. Thanks for doing this!

**Comment by disposab1e** [comment]
A few things I realized so far:

I need to apply:
```bash
oc adm policy add-cluster-role-to-user cluster-admin system:serviceaccount:argoproj:argocd-application-controller
```
to get it running in the moment. (perhaps the admin role might be enough, will test this)

When I create a new project and I try to run the example in this new project the guestbook-ui pod is not  starting. When I choose the existing `default` namespace all is fine. Not sure this is an operator issue or an argo-cd issue.

Not working:
```bash
oc new-project argoproj-examples
argocd app create guestbook \
  --repo https://github.com/argoproj/argocd-example-apps.git \
  --path guestbook \
  --dest-server https://kubernetes.default.svc \
  --dest-namespace argoproj-examples
```

Working:
```bash
oc new-project argoproj-examples
argocd app create guestbook \
  --repo https://github.com/argoproj/argocd-example-apps.git \
  --path guestbook \
  --dest-server https://kubernetes.default.svc \
  --dest-namespace default
```

**Comment by ch-stark** [comment]
I checked the guide from 
disposab1e and it is working fine using CRC on my laptop

**Pull request merged**
